version: '4'
services:
  client:
    image: client:client
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - ploop
  auth-server:
    image: auth:auth
    build:
      context: ./server/auth
      dockerfile: Dockerfile
    environment:
      - NODE_ENV="prod"
    env_file:
      - ./server/auth/.env
    ports:
      - "8001:8001"
    networks:
      - ploop
  encoding-server:
    image: encoding:encoding
    build:
      context: ./server/encoding
      dockerfile: Dockerfile
    environment:
      - NODE_ENV="prod"
    env_file:
      - ./server/encoding/.env
    ports:
      - "8006:8006"
    networks:
      - ploop
  api-gateway-server:
    image: gateway:gateway
    build:
      context: ./server/gateway
      dockerfile: Dockerfile
    environment:
      - NODE_ENV="prod"
    env_file:
      - ./server/gateway/.env
    ports:
      - "8000:8000"
    networks:
      - ploop
  notification-server:
    image: notification:notification
    build:
      context: ./server/notification
      dockerfile: Dockerfile
    environment:
      - NODE_ENV="prod"
    env_file:
      - ./server/notification/.env
    ports:
      - "8004:8004"
    networks:
      - ploop
  spray-server:
    image: spray:spray
    build:
      context: ./server/spray
      dockerfile: Dockerfile
    environment:
      - NODE_ENV="prod"
    env_file:
      - ./server/spray/.env
    ports:
      - "8005:8005"
    networks:
      - ploop
  upload-server:
    image: upload:upload
    build:
      context: ./server/upload
      dockerfile: Dockerfile
    environment:
      - NODE_ENV="prod"
    env_file:
      - ./server/upload/.env
    ports:
      - "8003:8003"
    networks:
      - ploop
  user-server:
    image: user:user
    build:
      context: ./server/user
      dockerfile: Dockerfile
    environment:
      - NODE_ENV="prod"
    env_file:
      - ./server/user/.env
    ports:
      - "8002:8002"
    networks:
      - ploop
networks:
  ploop: 
    driver: bridge